name: Typescript Compile and Tests
on:
  # This event type is dangerous
  pull_request_target:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**.ts'
jobs:
  Typescript_Compile_and_Tests:
    # Ensure the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    # PR is from the base repository, so it is only running code that was added by someone with write access, so it's trusted
    runs-on: ubuntu-latest
    env:
      FISH_BOT_ID: ${{ secrets.FISH_BOT_ID }}
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.FISH_BOT_ID }}
          private-key: ${{ secrets.FISH_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Git Config
        run: |
          git config --global core.autocrlf true
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/${{ github.repository }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true
      - name: Debug 1
        run: echo "Actor ID is ${{ github.actor_id }}"
      - name: Typescript Compile
        if: github.actor_id != env.FISH_BOT_ID
        run: pnpm run build
      - name: Check for modified files in build directory
        id: git-check
        run: |
          git add build/scripts
          echo "comitted=$(git commit -m "Automated TypeScript compile" > /dev/null; echo $?)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: github.actor_id != env.FISH_BOT_ID && steps.git-check.outputs.comitted == '0'
        run: git push
      - name: Run Tests
        if: github.actor_id == env.FISH_BOT_ID || steps.git-check.outputs.comitted != '0'
        run: pnpm run test
