name: Typescript Compile and Tests
on:
  # This event type is dangerous
  pull_request_target:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**.ts'
jobs:
  Typescript_Compile_and_Tests:
    # Ensure the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    # PR is from the base repository, so it is only running code that was added by someone with write access, so it's trusted
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Git Config
        run: git config --global core.autocrlf true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Install
        run: pnpm ci
      - name: Typescript Compile
        run: npm run build
      - name: Check for modified files
        id: git-check
        run: echo "modified=$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)" >> $GITHUB_OUTPUT
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated TypeScript compile"
          git push
      - name: Run Tests
        run: pnpm run test