name: PR Tests
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**.ts'
jobs:
  PR_Tests:
    # It's safe to run tests if the PR is from a fork
    # This workflow doesn't have write permissions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - name: Install
        run: pnpm ci
      - name: Run Tests
        # this also runs tsc
        run: pnpm run test
